// <auto-generated />
namespace AppG2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class a : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(a));
        
        string IMigrationMetadata.Id
        {
            get { return "201911080203363_a"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
